# Generated by Django 3.2.7 on 2021-09-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='somemodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='somemodel',
            name='other1',
            field=models.ManyToManyField(related_name='other1', to='someapp.SomeOtherModel'),
        ),
    ]
